CREATE TABLE IF NOT EXISTS messages (
    id BIGINT PRIMARY KEY,
    content TEXT,
    account_id BIGINT,
    inbox_id BIGINT,
    conversation_id BIGINT NOT NULL,
    message_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    private BOOLEAN,
    status VARCHAR(30),
    source_id TEXT,
    content_type VARCHAR(50),
    content_attributes TEXT,
    sender_type VARCHAR(50),
    sender_id BIGINT,
    additional_attributes TEXT,
    processed_message_content TEXT,
    sentiment TEXT,
    contact_id BIGINT,
    sistema_lead_id BIGINT,
    conversation_display_id BIGINT,
    id_sistema BIGINT,
    external_error TEXT,
    template_name TEXT,
    json_parse_status VARCHAR(20),
    incoming_category VARCHAR(50),
    matched_keyword VARCHAR(100),
    content_is_empty BOOLEAN NOT NULL DEFAULT FALSE,
    clean_message TEXT,
    encoding_repaired BOOLEAN NOT NULL DEFAULT FALSE,
    text_quality_status VARCHAR(40),
    CONSTRAINT chk_message_type
        CHECK (message_type IN ('incoming', 'outgoing', 'activity'))
);
